# Generated by Django 4.1.4 on 2022-12-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Informe o nome da categoria', max_length=120, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a categoria está ativa', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
        migrations.CreateModel(
            name='SubForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Informe o título do subfórum', max_length=120, verbose_name='Título')),
                ('description', models.TextField(help_text='Informe a descrição do subfórum', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o subfórum está ativo', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Informe o título do tópico', max_length=120, verbose_name='Título')),
                ('content', models.TextField(help_text='Informe o conteúdo do tópico', verbose_name='Conteúdo')),
                ('is_closed', models.BooleanField(default=False, help_text='Indica se o tópico está trancado', verbose_name='Trancado')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o tópico está ativo', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
