# Generated by Django 4.1.4 on 2023-01-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicresponse',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se a resposta está ativa', verbose_name='Ativo'),
        ),
    ]
